#Genera un archivo docker-compose que cuando se ejecute levante el sistema preguntado
#en el ejercicio opcional 3

#Una red
#Un volumen
#El motor de la base de datos de mongo
#La interfaz para gestionar la base de datos con mongo-express

#Configuraci贸n de mi-mongo
services:
  mi-mongo:
    image: mongo
    container_name: mi-mongo
    networks:
      - mi-red
    volumes:
      - mi-volumen:/data/db

#Configuraci贸n de mongo-express
mi-mongo-express:
  container_name: mi-mongo-express
  image: mongo-express #Imagen de mongo-express
  networks:
    - mi-red
  ports:
    - "8081:8081"
  environment:
    ME_CONFIG_MONGODB_SERVER: mi-mongo

#Definici贸n de redes
networks:
  mi-red:

#Definici贸n de volumenes
volumes:
  mi-volumen:
